services:
  - type: web
    name: brainchild
    env: python
    buildCommand: "pip install -r requirements.txt && flask db upgrade"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: brainchild-db
          property: connectionString
    disk:
      name: uploads
      mountPath: /opt/render/project/src/static/uploads
      sizeGB: 1

databases:
  - name: brainchild-db
    databaseName: brainchild
    user: brainchild_user
    plan: free